spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        connect-timeout: 360000
        response-timeout: 360000
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: auth-service
          uri: https://service-authorization-b1jx.onrender.com
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: https://service-user-data.onrender.com
          predicates:
            - Path=/ping
logging:
  level:
    reactor.netty: INFO
    org.springframework.cloud.gateway: TRACE

