spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        connect-timeout: 360000
        response-timeout: 360000
        ssl:
          useInsecureTrustManager: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: auth-service
          uri: https://service-authorization-b1jx.onrender.com
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin
        - id: user-service
          uri: https://service-user-qxpc.onrender.com
          predicates:
            - Path=/user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin
        - id: advertisement-service
          uri: https://service-advertisement.onrender.com
          predicates:
            - Path=/ad/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin


logging:
  level:
    reactor.netty: INFO
    org.springframework.cloud.gateway: TRACE

