spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 360000
        response-timeout: 360000
        ssl:
          useInsecureTrustManager: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: auth-service
          uri: https://service-authorization-b1jx.onrender.com
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET,POST
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 300ms
                  factor: 2

        - id: user-service
          uri: https://service-user-qxpc.onrender.com
          predicates:
            - Path=/user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin

        - id: advertisement-service
          uri: lb://advertisement-service
          predicates:
            - Path=/product/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET,POST
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 300ms
                  factor: 2

        - id: chat-service
          uri: https://service-chat-t47s.onrender.com
          predicates:
            - Path=/chat/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET,POST
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 300ms
                  factor: 2
    discovery:
      client:
        simple:
          instances:
#            advertisement-service:
#              - uri: http://34.76.90.90:8080
#                metadata:
#                  weight: 3

              - uri: https://service-advertisement-r8dt.onrender.com
                metadata:
                  weight: 1
logging:
  level:
    reactor.netty: INFO
    org.springframework.cloud.gateway: TRACE

auth:
  service:
    base-url: https://service-authorization-b1jx.onrender.com
user:
  service:
    base-url: https://service-user-qxpc.onrender.com


